untdf_reservas_aulas_edificio:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/edificio.yml"
    prefix:   /edificio

untdf_reservas_aulas_carrera:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/carrera.yml"
    prefix:   /carrera

untdf_reservas_aulas_docente:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/docente.yml"
    prefix:   /docente

untdf_reservas_aulas_fechaespecial:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/fechaespecial.yml"
    prefix:   /fechaespecial

untdf_reservas_aulas_tipoactividad:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/tipoactividad.yml"
    prefix:   /tipoactividad

untdf_reservas_aulas_aulas:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/aula.yml"
    prefix:   /aulas

untdf_reservas_aulas_edificios:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/edificio.yml"
    prefix:   /edificios

untdf_reservas_aulas_homepage:
    path:     /hello/{name}
    defaults: { _controller: UNTDFReservasAulasBundle:Default:index }
    
ReservasMain:
    path: /
    defaults: { _controller: UNTDFReservasAulasBundle:ReservasMain:index }

