untdf_reservas_aulas_reserva:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/reserva.yml"
    prefix:   /admin/reserva

untdf_reservas_aulas_recurso:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/recurso.yml"
    prefix:   /admin/recurso

untdf_reservas_aulas_actividad:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/actividad.yml"
    prefix:   /admin/actividad

untdf_reservas_aulas_curso:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/curso.yml"
    prefix:   /admin/curso
    
untdf_reservas_aulas_carrera:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/carrera.yml"
    prefix:   /admin/carrera

untdf_reservas_aulas_docente:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/docente.yml"
    prefix:   /admin/docente

untdf_reservas_aulas_fechaespecial:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/fechaespecial.yml"
    prefix:   /admin/fechaespecial

untdf_reservas_aulas_tipoactividad:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/tipoactividad.yml"
    prefix:   /admin/tipoactividad

untdf_reservas_aulas_aulas:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/aula.yml"
    prefix:   /admin/aulas

untdf_reservas_aulas_edificios:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/edificio.yml"
    prefix:   /admin/edificios
    
ReservasMain:
    path: /
    defaults: { _controller: UNTDFReservasAulasBundle:ReservasMain:index }

