untdf_reservas_aulas_carrera:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/carrera.yml"
    prefix:   /carrera

untdf_reservas_aulas_docente:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/docente.yml"
    prefix:   /docente

untdf_reservas_aulas_fechaespecial:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/fechaespecial.yml"
    prefix:   /fechaespecial

untdf_reservas_aulas_tipoactividad:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/tipoactividad.yml"
    prefix:   /tipoactividad

untdf_reservas_aulas_aulas:
    resource: "@UNTDFReservasAulasBundle/Resources/config/routing/aula.yml"
    prefix:   /aulas

untdf_reservas_aulas_homepage:
    path:     /hello/{name}
    defaults: { _controller: UNTDFReservasAulasBundle:Default:index }

edificios:
    path: /edificios
    defaults: { _controller: UNTDFReservasAulasBundle:Edificio:index }
    
edificio/agregar:
    path: /edificio/agregar
    defaults: { _controller: UNTDFReservasAulasBundle:Edificio:new }

edificio/crear:
    path: /edificio/crear
    defaults: { _controller: UNTDFReservasAulasBundle:Edificio:create }
    methods : [POST]

edificio/edit:
    path: /edificio/edit/{id}
    defaults: { _controller: UNTDFReservasAulasBundle:Edificio:edit }

edificio/update:
    path: /edificio/update/{id}
    defaults: { _controller: UNTDFReservasAulasBundle:Edificio:update }
    methods : [POST]

edificio/borrar:
    path: /edificio/borrar/{id}
    defaults: { _controller: UNTDFReservasAulasBundle:Edificio:remove }

edificio/ver:
    path: /edificio/ver/{id}
    defaults: { _controller: UNTDFReservasAulasBundle:Edificio:show }
    


