UNTDF\ReservasAulasBundle\Entity\Edificio:
    properties:
        nombre:
            - NotBlank:  
                message: no puede estar en blanco.
            - NotNull:
                message: no puede ser nulo.
            
