actividad:
    path:     /
    defaults: { _controller: "UNTDFReservasAulasBundle:Actividad:index" }

actividad_show:
    path:     /{id}/show
    defaults: { _controller: "UNTDFReservasAulasBundle:Actividad:show" }

actividad_new:
    path:     /new
    defaults: { _controller: "UNTDFReservasAulasBundle:Actividad:new" }

actividad_create:
    path:     /create
    defaults: { _controller: "UNTDFReservasAulasBundle:Actividad:create" }
    methods:  POST

actividad_edit:
    path:     /{id}/edit
    defaults: { _controller: "UNTDFReservasAulasBundle:Actividad:edit" }

actividad_update:
    path:     /{id}/update
    defaults: { _controller: "UNTDFReservasAulasBundle:Actividad:update" }
    methods:  [POST, PUT]

actividad_delete:
    path:     /{id}/delete
    defaults: { _controller: "UNTDFReservasAulasBundle:Actividad:delete" }
    methods:  [POST, DELETE]
