carrera:
    path:     /
    defaults: { _controller: "UNTDFReservasAulasBundle:Carrera:index" }

carrera_show:
    path:     /{id}/show
    defaults: { _controller: "UNTDFReservasAulasBundle:Carrera:show" }

carrera_new:
    path:     /new
    defaults: { _controller: "UNTDFReservasAulasBundle:Carrera:new" }

carrera_create:
    path:     /create
    defaults: { _controller: "UNTDFReservasAulasBundle:Carrera:create" }
    methods:  POST

carrera_edit:
    path:     /{id}/edit
    defaults: { _controller: "UNTDFReservasAulasBundle:Carrera:edit" }

carrera_update:
    path:     /{id}/update
    defaults: { _controller: "UNTDFReservasAulasBundle:Carrera:update" }
    methods:  [POST, PUT]

carrera_delete:
    path:     /{id}/delete
    defaults: { _controller: "UNTDFReservasAulasBundle:Carrera:delete" }
    methods:  [POST, DELETE]
