docente:
    path:     /
    defaults: { _controller: "UNTDFReservasAulasBundle:Docente:index" }

docente_show:
    path:     /{id}/show
    defaults: { _controller: "UNTDFReservasAulasBundle:Docente:show" }

docente_new:
    path:     /new
    defaults: { _controller: "UNTDFReservasAulasBundle:Docente:new" }

docente_create:
    path:     /create
    defaults: { _controller: "UNTDFReservasAulasBundle:Docente:create" }
    methods:  POST

docente_edit:
    path:     /{id}/edit
    defaults: { _controller: "UNTDFReservasAulasBundle:Docente:edit" }

docente_update:
    path:     /{id}/update
    defaults: { _controller: "UNTDFReservasAulasBundle:Docente:update" }
    methods:  [POST, PUT]

docente_delete:
    path:     /{id}/delete
    defaults: { _controller: "UNTDFReservasAulasBundle:Docente:delete" }
    methods:  [POST, DELETE]
