reserva:
    path:     /
    defaults: { _controller: "UNTDFReservasAulasBundle:Reserva:index" }

reserva_show:
    path:     /{id}/show
    defaults: { _controller: "UNTDFReservasAulasBundle:Reserva:show" }

reserva_new:
    path:     /new
    defaults: { _controller: "UNTDFReservasAulasBundle:Reserva:new" }

reserva_create:
    path:     /create
    defaults: { _controller: "UNTDFReservasAulasBundle:Reserva:create" }
    methods:  POST

reserva_edit:
    path:     /{id}/edit
    defaults: { _controller: "UNTDFReservasAulasBundle:Reserva:edit" }

reserva_update:
    path:     /{id}/update
    defaults: { _controller: "UNTDFReservasAulasBundle:Reserva:update" }
    methods:  [POST, PUT]

reserva_delete:
    path:     /{id}/delete
    defaults: { _controller: "UNTDFReservasAulasBundle:Reserva:delete" }
    methods:  [POST, DELETE]
