tipoactividad:
    path:     /
    defaults: { _controller: "UNTDFReservasAulasBundle:TipoActividad:index" }

tipoactividad_show:
    path:     /{id}/show
    defaults: { _controller: "UNTDFReservasAulasBundle:TipoActividad:show" }

tipoactividad_new:
    path:     /new
    defaults: { _controller: "UNTDFReservasAulasBundle:TipoActividad:new" }

tipoactividad_create:
    path:     /create
    defaults: { _controller: "UNTDFReservasAulasBundle:TipoActividad:create" }
    methods:  POST

tipoactividad_edit:
    path:     /{id}/edit
    defaults: { _controller: "UNTDFReservasAulasBundle:TipoActividad:edit" }

tipoactividad_update:
    path:     /{id}/update
    defaults: { _controller: "UNTDFReservasAulasBundle:TipoActividad:update" }
    methods:  [POST, PUT]

tipoactividad_delete:
    path:     /{id}/delete
    defaults: { _controller: "UNTDFReservasAulasBundle:TipoActividad:delete" }
    methods:  [POST, DELETE]
